"""empty message

Revision ID: 0068713354d8
Revises: 3f0cb61bbf6b
Create Date: 2020-10-16 13:12:31.890009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0068713354d8'
down_revision = '3f0cb61bbf6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'roles', 'user', ['user_id'], ['id'])
    op.drop_column('user', 'role_id')
    op.drop_column('user', 'permissions')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('permissions', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'user_id')
    # ### end Alembic commands ###
