"""empty message

Revision ID: 0b61dc42c765
Revises: 12ab1d6ab3f2
Create Date: 2020-10-24 12:31:55.240737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b61dc42c765'
down_revision = '12ab1d6ab3f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_email'), 'messages', ['email'], unique=True)
    op.create_index(op.f('ix_messages_uname'), 'messages', ['uname'], unique=True)
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_index(op.f('ix_messages_uname'), table_name='messages')
    op.drop_index(op.f('ix_messages_email'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
