"""empty message

Revision ID: 12ab1d6ab3f2
Revises: e4a54f3a0681
Create Date: 2020-10-21 14:38:34.238807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12ab1d6ab3f2'
down_revision = 'e4a54f3a0681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about', sa.Text(), nullable=True))
    op.drop_column('user', 'info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('info', mysql.TEXT(), nullable=True))
    op.drop_column('user', 'about')
    # ### end Alembic commands ###
