"""empty message

Revision ID: 3f0cb61bbf6b
Revises: 4ac8791f5f7c
Create Date: 2020-10-16 13:01:48.953113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f0cb61bbf6b'
down_revision = '4ac8791f5f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=False))
    op.drop_index('role', table_name='user')
    op.create_foreign_key(None, 'user', 'roles', ['role_id'], ['id'])
    op.drop_column('user', 'permissions')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('permissions', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_index('role', 'user', ['role'], unique=True)
    op.drop_column('user', 'role_id')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
