"""empty message

Revision ID: 66ce08517edd
Revises: e1c7cdbb3f9f
Create Date: 2021-02-09 09:53:16.842457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ce08517edd'
down_revision = 'e1c7cdbb3f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('s_category', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 's_category')
    # ### end Alembic commands ###
