"""empty message

Revision ID: 6bdfeebe06c5
Revises: b04678e62e00
Create Date: 2021-02-20 16:05:20.745565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bdfeebe06c5'
down_revision = 'b04678e62e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('replies_ibfk_1', 'replies', type_='foreignkey')
    op.create_foreign_key(None, 'replies', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'replies', type_='foreignkey')
    op.create_foreign_key('replies_ibfk_1', 'replies', 'comments', ['comment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
