"""empty message

Revision ID: 817cc859ff16
Revises: 2cadcd287c0d
Create Date: 2021-03-22 18:52:18.189508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '817cc859ff16'
down_revision = '2cadcd287c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('replies_ibfk_1', 'replies', type_='foreignkey')
    op.drop_column('replies', 'comment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('comment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('replies_ibfk_1', 'replies', 'comments', ['comment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
