"""empty message

Revision ID: a932eab2ff7c
Revises: 5b620ca5d2bd
Create Date: 2020-10-24 13:08:18.095024

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a932eab2ff7c'
down_revision = '5b620ca5d2bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message', sa.Text(), nullable=False))
    op.add_column('messages', sa.Column('name', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_messages_name'), 'messages', ['name'], unique=True)
    op.drop_index('ix_messages_uname', table_name='messages')
    op.drop_column('messages', 'messo')
    op.drop_column('messages', 'uname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('uname', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('messages', sa.Column('messo', mysql.TEXT(), nullable=False))
    op.create_index('ix_messages_uname', 'messages', ['uname'], unique=True)
    op.drop_index(op.f('ix_messages_name'), table_name='messages')
    op.drop_column('messages', 'name')
    op.drop_column('messages', 'message')
    # ### end Alembic commands ###
