"""empty message

Revision ID: d34791a2044d
Revises: d1e7fa340e81
Create Date: 2020-10-21 10:15:39.950497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd34791a2044d'
down_revision = 'd1e7fa340e81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'stitle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('stitle', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
