"""empty message

Revision ID: e1c7cdbb3f9f
Revises: a932eab2ff7c
Create Date: 2020-10-24 13:17:33.692351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c7cdbb3f9f'
down_revision = 'a932eab2ff7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_email', table_name='messages')
    op.create_index(op.f('ix_messages_email'), 'messages', ['email'], unique=False)
    op.drop_index('ix_messages_name', table_name='messages')
    op.create_index(op.f('ix_messages_name'), 'messages', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_name'), table_name='messages')
    op.create_index('ix_messages_name', 'messages', ['name'], unique=True)
    op.drop_index(op.f('ix_messages_email'), table_name='messages')
    op.create_index('ix_messages_email', 'messages', ['email'], unique=True)
    # ### end Alembic commands ###
