"""empty message

Revision ID: e4a54f3a0681
Revises: e8260b9db654
Create Date: 2020-10-21 14:36:58.380368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4a54f3a0681'
down_revision = 'e8260b9db654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('info', sa.Text(), nullable=True))
    op.drop_column('user', 'about')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about', mysql.VARCHAR(length=300), nullable=True))
    op.drop_column('user', 'info')
    # ### end Alembic commands ###
